name: Gunluk Haber Botu Calistirici

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari depodan cek
        uses: actions/checkout@v3

      - name: Python 3.9 Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri yukle
        run: |
          pip install -r requirements.txt

      - name: Haber Botunu Calistir
        env:
          MAIL_ADRESI: ${{ secrets.MAIL_ADRESI }}
          MAIL_SIFRESI: ${{ secrets.MAIL_SIFRESI }}
          # Buraya OpenAI yerine HuggingFace kullanacaksak onun secret'ını ekleyeceğiz
        run: python daily_news.py
